/**
 * Core types for the Turing game server
 */

export interface ChatMessage {
	id: number
	sender: string
	senderId: string
	text: string
	type?: "system" | "normal" | "error" // Optional type for message styling
	timestamp: number // Unix epoch milliseconds when the message was originally created
	roomId?: string // Optional room identifier for multi-channel support
}

// Player interfaces
export interface Player {
	id: string
	name: string // Original name chosen by user or assigned to AI
	isAI: boolean
	anonymizedName?: string // Name used in game modes, generated by server
	bio?: string // User-set bio, shown on hover
}

export interface PublicPlayer {
	id: string
	name: string
	isAI?: boolean // Optional - only included in playground mode
	bio?: string // User-set bio, shown on hover
	persona?: PlayerPersona
}

export interface PlayerPersona {
	profile: string
	gameSettings?: {
		// Optional as not all players are AI
		enabled: boolean
		autoInvite: boolean
		strategy: string
	}
	chatSettings?: {
		// Optional as not all players are AI
		enabled: boolean
		autoInvite: boolean
	}
	// Retaining personality traits for now as they might be used on client
	personality?: {
		traits: string[]
		communicationStyle: string
		interests: string[]
		background: string
		typingPatterns: string
		commonPhrases: string[]
		emojiUsage: string
	}
}

// Room interfaces
export interface Room {
	players: Map<string, Player> // Map socket id to Player
	messages: ChatMessage[] // Store recent messages for context
	lastHumanActivity: number // Timestamp of last human interaction
	promptTimers?: NodeJS.Timeout[] // timers for scheduled system prompts
	topic?: string // Optional topic/description for the channel
}

// Playground-specific interfaces
export interface PlaygroundSettings {
	model: string
	temperature: number
	maxTokens: number
}

export interface PlaygroundRoom extends Room {
	isPlayground: boolean
	settings: PlaygroundSettings
}
